Allow stats to be silenced
natefaubion/purescript-psa-utils pull request #4
Opened 2017-08-03 05:13 UTC by Rufflewind

2017-08-03 16:11 UTC, natefaubion requested changes

2017-08-03 16:11 UTC, natefaubion commented on src/Psa/Printer/Default.purs
> +    _ -> renderVerboseStats
Can we add an appropriate data type instead of using `Int`?

```purescript
data StatOption = NoStats | CompactStats | VerboseStats
```

2017-08-03 17:08 UTC, Rufflewind commented on src/Psa/Printer/Default.purs
> +    _ -> renderVerboseStats
Done.

2017-11-21 16:35 UTC, natefaubion approved these changes

2018-01-06 17:31 UTC, merged